---

- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - vars/postgres.yml
  roles:
    - software
#    - ansible-role-postgresql
#    - ansible-role-postgis

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - vars/postgres.yml
  roles:
    - enviroment
      #    - fonts
      #- dropbox
